name: app
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - name: Zip output
              uses: papeloto/action-zip@v1
              with:
                  files: .next/
                  dest: playground-next.zip
            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: playground-next
                  path: playground-next.zip
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Get artifact
              uses: actions/download-artifact@v2
              with:
                  name: playground-next
            - name: Copy artifact
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.PROD_HOST }}
                  username: ${{ secrets.PROD_USERNAME }}
                  key: ${{ secrets.PROD_KEY }}
                  source: 'playground-next.zip'
                  target: '/home/playground'
            - name: Upgrade
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.PROD_HOST }}
                  username: ${{ secrets.PROD_USERNAME }}
                  key: ${{ secrets.PROD_KEY }}
                  script: |
                      cd /home/playground
                      zip -r "$(date +%Y%m%d_%H%M%S)_next.zip" next/
                      rm -rf next
                      unzip playground-next.zip -d next
                      rm playground-next.zip
